### ISSUE TITLE
Contributor guidelines

### ISSUE THREAD

**Issue by misterspeedy** [misterspeedy/FsExcel#7]
Need contributor guidelines including VS Code setup, other IDE setup, workflow...

**Comment by johncj-improving** [comment]
Based on my experience, I believe the appropriate first steps are as follows:

1. Open a command shell, navigate to /src and run dotnet build. Otherwise, the local load will fail later.
2. Open the FsExcel folder in VSCode and follow the instructions you linked to above for managing automatic tasks
3. Close and re-open the FsExcel folder so that the watch tasks run.
4. After the watch task generates the actuals, run dotnet test in /src 

Wishlist:
1. Name the expected files differently. Excel can't open two files with the same name at the same time, even if they come from different directories. That makes it more difficult to compare actual to expected. Perhaps the expected files could be named {actual}-expected.xls
2. The tests currently don't tell you which files generated the error. It would be awesome if the error messages were more informative. I'm not familiar enough with xUnit to suggest how to solve that issue.

**Comment by misterspeedy** [comment]
Done.
